jdk:
  - openjdk11
  
stages:
  - unitAndIntegrationTest
  - continousDelivery
  - continousDeployment
  
before_install:
  - chmod +x gradlew
  
install:
 #   - npm install newman
    
jobs:
  include:
    - stage: unitAndIntegrationTest
      script: ./gradlew test 
    - stage: continousDelivery
      deploy:
        provider: heroku
        api-key: $HEROKU_API_KEY
        app: $HEROKU_STAGING_APP
      after_success:
    #  script: newman run src/test/java/system/collection/uek223_advanced.postman_collection.json -e src/test/java/system/environment/uek223_advanced.postman_environment.json
    - stage: continousDeployment
